### ISSUE TITLE
Cannot render the webpage in Microsoft Edge and Postman

### ISSUE THREAD

**Issue by namanhishere** [radiantly/you-cant-download-this-image#2]
I Currently using Version 96.0.1054.34 in Windows 11. I got a same problem using Postman (win32 10.0.22000 / x64) also. It may cause from getting image request.
![image](https://user-images.githubusercontent.com/53372786/143679237-bf875e1f-0bd9-4e4c-bb2f-f12a74a8fa1f.png)
![image](https://user-images.githubusercontent.com/53372786/143679360-797ee0f6-45c2-480a-80ac-21f32f41af67.png)

**Comment by radiantly** [comment]
This was a server issue that has since been resolved. Thanks for opening an issue though!
